# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN101", # Missing type annotation for `self` in method
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter
    "ISC001", # incompatible with formatter
    "TC001", # Move application import into a type-checking block
    "TC002", # Move third-party import into a type-checking block
    "E501", # Line too long
    "ANN201", # Missing return type annotation for public function
    "ANN202", # Missing return type annotation for private function
    "ANN204", # Missing return type annotation for special method
    "ANN001", # Missing type annotation for function argument
    "PERF401", # Use a list comprehension to create a transformed list
    "PERF102", # Use the values() method instead of items()
    "B007", # Loop control variable not used within loop body
    "D102", # Missing docstring in public method
    "F401", # Module imported but unused
    "BLE001", # Do not catch blind exception
    "RUF015", # Prefer next(iter()) over single element slice
    "RUF013", # PEP 484 prohibits implicit Optional
    "PLR2004", # Magic value used in comparison
    "TRY301", # Abstract raise to an inner function
    "TRY003", # Avoid specifying long messages outside the exception class
    "EM101", # Exception must not use a string literal
    "FBT003", # Boolean positional value in function call
    "PLR0911", # Too many return statements
    "D107", # Missing docstring in __init__
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25